-- ADC Academy - Supabase Schema (PostgreSQL)
-- This file defines the tables for the ADC Academy & Skill Acquisition Transformation.
-- It includes Row Level Security (RLS) policies for data protection.

-- --- 1. CLEANUP ---
-- Use CASCADE to safely handle dependent objects (like foreign keys).
DROP TABLE IF EXISTS public.roadmap_steps CASCADE;
-- DROP TABLE IF EXISTS public.generated_roadmaps CASCADE;
-- DROP TABLE IF EXISTS public.lessons CASCADE;
-- DROP TABLE IF EXISTS public.courses CASCADE;
-- DROP TABLE IF EXISTS public.users CASCADE;
-- DROP TABLE IF EXISTS public.messages CASCADE;
-- DROP TABLE IF EXISTS public.blog_posts CASCADE;
-- DROP TABLE IF EXISTS public.subscribers CASCADE;
-- DROP TABLE IF EXISTS public.chat_messages CASCADE;

-- --- 2. TABLES ---

-- USERS TABLE
CREATE TABLE IF NOT EXISTS public.users (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    username TEXT UNIQUE NOT NULL,
    email TEXT UNIQUE NOT NULL,
    password TEXT NOT NULL,
    role TEXT DEFAULT 'student',
    streak INTEGER DEFAULT 1,
    full_name TEXT,
    state TEXT,
    lga TEXT,
    gender TEXT,
    age INTEGER,
    study_reminder_time TEXT,
    daily_study_hours NUMERIC DEFAULT 0,
    avatar_url TEXT,
    wallpaper_url TEXT,
    is_admin BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    last_login TIMESTAMPTZ
);

-- COURSES TABLE
CREATE TABLE IF NOT EXISTS public.courses (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    title TEXT NOT NULL,
    description TEXT,
    author_id BIGINT REFERENCES public.users(id),
    date_posted TIMESTAMPTZ DEFAULT NOW()
);

-- LESSONS TABLE
CREATE TABLE IF NOT EXISTS public.lessons (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    course_id BIGINT REFERENCES public.courses(id) ON DELETE CASCADE,
    title TEXT NOT NULL,
    content TEXT, -- For text lessons
    file_path TEXT, -- For PDF/Video/YouTube ID
    lesson_type TEXT NOT NULL, -- 'text', 'file', 'video', 'youtube'
    date_posted TIMESTAMPTZ DEFAULT NOW()
);

-- GENERATED ROADMAPS TABLE
CREATE TABLE IF NOT EXISTS public.generated_roadmaps (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id BIGINT REFERENCES public.users(id) ON DELETE CASCADE,
    goal TEXT NOT NULL,
    content TEXT,
    image_url TEXT,
    date_created TIMESTAMPTZ DEFAULT NOW()
);

-- ROADMAP STEPS TABLE
CREATE TABLE IF NOT EXISTS public.roadmap_steps (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    roadmap_id BIGINT REFERENCES public.generated_roadmaps(id) ON DELETE CASCADE,
    step_number INTEGER NOT NULL,
    title TEXT NOT NULL,
    description TEXT,
    youtube_queries TEXT, -- Stored as JSON string
    lecture_content TEXT,
    audio_url TEXT,
    status TEXT DEFAULT 'not_started',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- --- OTHER LEGACY/UTILITY TABLES (Migrated to Postgres) ---

CREATE TABLE IF NOT EXISTS public.messages (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NOT NULL,
    email TEXT NOT NULL,
    subject TEXT,
    message TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.blog_posts (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    title TEXT NOT NULL,
    content TEXT NOT NULL,
    author TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.subscribers (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    email TEXT UNIQUE NOT NULL,
    subscribed_at TIMESTAMPTZ DEFAULT NOW()
);

-- CHAT MESSAGES TABLE (for AI Tutor)
CREATE TABLE IF NOT EXISTS public.chat_sessions (
    id TEXT PRIMARY KEY, -- Using the UUID generated by frontend or backend
    user_id BIGINT REFERENCES public.users(id) ON DELETE CASCADE,
    title TEXT DEFAULT 'New Chat',
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.chat_messages (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    content TEXT NOT NULL,
    sender_id BIGINT, -- REFERENCES public.users(id) - can be NULL for AI/System
    user_id BIGINT REFERENCES public.users(id) ON DELETE CASCADE,
    session_id TEXT NOT NULL, -- UUID or simple session identifier
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- --- 3. SECURITY (Row Level Security) ---

-- Enable RLS
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.courses ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.lessons ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.generated_roadmaps ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.roadmap_steps ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.blog_posts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.subscribers ENABLE ROW LEVEL SECURITY;

-- POLICIES for USERS
CREATE POLICY "Allow public registration" ON public.users FOR INSERT WITH CHECK (TRUE);
CREATE POLICY "Allow backend access users" ON public.users FOR ALL USING (TRUE);

-- POLICIES for OTHER TABLES
CREATE POLICY "Allow backend access courses" ON public.courses FOR ALL USING (TRUE);
CREATE POLICY "Allow backend access lessons" ON public.lessons FOR ALL USING (TRUE);
CREATE POLICY "Allow backend access roadmaps" ON public.generated_roadmaps FOR ALL USING (TRUE);
CREATE POLICY "Allow backend access steps" ON public.roadmap_steps FOR ALL USING (TRUE);
-- POLICY: Chat Sessions
CREATE POLICY "Allow backend access chat_sessions" ON public.chat_sessions FOR ALL USING (TRUE);
CREATE POLICY "Allow backend access chat" ON public.chat_messages FOR ALL USING (TRUE);
CREATE POLICY "Allow backend access messages" ON public.messages FOR ALL USING (TRUE);
CREATE POLICY "Allow backend access blog" ON public.blog_posts FOR ALL USING (TRUE);
CREATE POLICY "Allow backend access subscribers" ON public.subscribers FOR ALL USING (TRUE);

-- --- 4. VIEWS & INDEXES ---
CREATE INDEX IF NOT EXISTS idx_users_email ON public.users(email);
CREATE INDEX IF NOT EXISTS idx_roadmaps_user_id ON public.generated_roadmaps(user_id);
CREATE INDEX IF NOT EXISTS idx_steps_roadmap_id ON public.roadmap_steps(roadmap_id);
CREATE INDEX IF NOT EXISTS idx_lessons_course_id ON public.lessons(course_id);

-- --- 5. INITIAL DATA (Optional) ---
INSERT INTO public.users (username, email, password, role, is_admin)
VALUES ('admin', 'admin@kusmus.com', 'Ejiro_26', 'admin', TRUE)
ON CONFLICT (email) DO NOTHING;
