"""Add solution and test cases to Assignment model

Revision ID: bd6befece9a2
Revises: e8cda407c67c
Create Date: 2025-10-06 22:15:13.790948

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd6befece9a2'
down_revision = 'e8cda407c67c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assignment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('solution_code', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('test_cases', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assignment', schema=None) as batch_op:
        batch_op.drop_column('test_cases')
        batch_op.drop_column('solution_code')

    # ### end Alembic commands ###
